name: Client CI and Deployment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd client
          npm ci 
          npm run build --if-present
  build-push-gcr:
    uses: jesseokeya/workflows/.github/workflows/gcp-push-artifact-registry.yml@main
    with:
      working-directory: ./client
    secrets: inherit
